import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A0A0A' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 20,
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: -0.5,
  },
  themeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#161616',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#222',
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 100,
  },

  // Cartão Principal
  cardPerfil: {
    backgroundColor: '#161616',
    borderRadius: 32,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#222',
    marginBottom: 24,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#202020',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#00C853',
  },
  avatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#00C853',
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#161616',
  },
  nomeUsuario: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 4,
  },
  tagEntregador: {
    backgroundColor: 'rgba(0, 200, 83, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    marginBottom: 20,
  },
  tagTexto: {
    color: '#00C853',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },

  btnEditarPerfil: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#202020',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  btnEditarTexto: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },

  // Meta Diária
  secaoTitle: {
    color: '#666',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 12,
    marginLeft: 8,
  },
  cardMeta: {
    backgroundColor: '#161616',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#222',
    marginBottom: 24,
  },
  metaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  metaIconBox: {
    backgroundColor: 'rgba(0, 200, 83, 0.1)',
    padding: 12,
    borderRadius: 16,
  },
  metaLabel: {
    color: '#888',
    fontSize: 12,
    fontWeight: 'bold',
  },
  metaInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0A0A0A',
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#333',
  },
  metaCurrency: {
    color: '#666',
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 8,
  },
  metaInput: {
    flex: 1,
    color: '#00C853',
    fontSize: 24,
    fontWeight: '900',
    paddingVertical: 12,
  },
  btnSalvarMeta: {
    backgroundColor: '#00C853',
    padding: 12,
    borderRadius: 12,
    marginLeft: 8,
  },

  // Veículo
  cardVeiculo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#161616',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#222',
    marginBottom: 24,
  },
  veiculoInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  veiculoIconBox: {
    backgroundColor: '#202020',
    padding: 16,
    borderRadius: 16,
  },
  veiculoModelo: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  veiculoPlaca: {
    color: '#888',
    fontSize: 12,
    marginTop: 4,
  },
  btnEditarVeiculo: {
    padding: 12,
    backgroundColor: '#202020',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#333',
  },

  // Grid de Ações
  gridAcoes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 32,
  },
  btnAcao: {
    width: '48%',
    backgroundColor: '#161616',
    padding: 20,
    borderRadius: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#222',
    gap: 12,
  },
  btnAcaoTexto: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  // Logout
  btnLogout: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 20,
    marginBottom: 20,
    borderRadius: 24,
    backgroundColor: 'rgba(244, 67, 54, 0.05)',
  },
  btnLogoutTexto: {
    color: '#F44336',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});
