import { StyleSheet } from 'react-native';

export const exploreStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
    paddingTop: 50,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFF',
  },
  tabContainer: { height: 50, marginBottom: 10 },
  tabButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginHorizontal: 4,
    borderRadius: 20,
    backgroundColor: '#202020',
    justifyContent: 'center',
    height: 40,
  },
  tabButtonActive: { backgroundColor: '#00C853' },
  tabText: { color: '#888', fontWeight: '600' },
  tabTextActive: { color: '#0A0A0A' },
  actionsBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#222',
  },
  infoText: { color: '#666', fontSize: 12 },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  deleteText: { color: '#FF4444', fontSize: 12 },
  card: {
    backgroundColor: '#161616',
    marginHorizontal: 20,
    marginTop: 10,
    padding: 15,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#00C853',
  },
  cardIndex: {
    position: 'absolute',
    right: 10,
    top: 10,
    color: '#333',
    fontWeight: 'bold',
    fontSize: 10,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  key: {
    color: '#888',
    fontWeight: 'bold',
    marginRight: 6,
    fontSize: 12,
  },
  value: { color: '#EEE', fontSize: 12, flex: 1 },
  emptyText: {
    color: '#555',
    textAlign: 'center',
    marginTop: 50,
  },
  listContent: {
    paddingBottom: 20,
  },
});
