import { StyleSheet } from 'react-native';

export const inlineStyles = StyleSheet.create({
  inline1: {
                flexDirection: 'row',
                alignItems: 'center',
                gap: 8,
              },
  inline2: {
                color: '#00C853',
                fontSize: 12,
                fontWeight: 'bold',
              },
  inline3: {
                flexDirection: 'row',
                alignItems: 'center',
                gap: 8,
              },
  inline4: {
                color: '#00C853',
                fontSize: 12,
                fontWeight: 'bold',
              },
  inline5: { padding: 20, alignItems: 'center' },
  inline6: {
                      flexDirection: 'row',
                      alignItems: 'center',
                    },
  inline7: {
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.85)',
            justifyContent: 'center',
            alignItems: 'center',
          },
  inline8: { marginBottom: 20 },
  inline9: { color: '#FFF', fontWeight: 'bold' },
  inline10: { gap: 20 },
  inline11: { alignItems: 'center' },
  inline12: {
                        width: 180,
                        height: 60,
                        resizeMode: 'contain',
                        tintColor: '#00C853',
                      },
  inline13: {
                        color: '#FFF',
                        fontSize: 16,
                        textTransform: 'uppercase',
                        letterSpacing: 3,
                        marginTop: 4,
                      },
  inline14: {
                      backgroundColor: '#161616',
                      padding: 24,
                      borderRadius: 20,
                      alignItems: 'center',
                      borderWidth: 1,
                      borderColor: '#333',
                    },
  inline15: {
                        color: '#00C853',
                        fontSize: 26,
                        fontWeight: 'bold',
                        textAlign: 'center',
                      },
  inline16: {
                        color: '#AAA',
                        fontSize: 16,
                        textAlign: 'center',
                        marginTop: 12,
                        lineHeight: 24,
                      },
  inline17: {
                          color: '#FFF',
                          fontWeight: 'bold',
                        },
  inline18: {
                      flexDirection: 'row',
                      gap: 12,
                    },
  inline19: {
                        flex: 1,
                        backgroundColor: '#161616',
                        padding: 20,
                        borderRadius: 20,
                        borderWidth: 1,
                        borderColor: '#333',
                        alignItems: 'center',
                      },
  inline20: {
                          color: '#888',
                          fontSize: 14,
                          textTransform: 'uppercase',
                          fontWeight: 'bold',
                        },
  inline21: {
                          color: '#FFF',
                          fontSize: 24,
                          fontWeight: '900',
                          marginTop: 8,
                        },
  inline22: {
                        flex: 1,
                        backgroundColor: '#161616',
                        padding: 20,
                        borderRadius: 20,
                        borderWidth: 1,
                        borderColor: '#333',
                        alignItems: 'center',
                      },
  inline23: {
                          color: '#888',
                          fontSize: 14,
                          textTransform: 'uppercase',
                          fontWeight: 'bold',
                        },
  inline24: {
                          color: '#00C853',
                          fontSize: 24,
                          fontWeight: '900',
                          marginTop: 8,
                        },
  inline25: {
                      backgroundColor: '#161616',
                      padding: 20,
                      borderRadius: 20,
                      borderWidth: 1,
                      borderColor: '#333',
                    },
  inline26: {
                        color: '#FFF',
                        fontWeight: '900',
                        marginBottom: 16,
                        fontSize: 16,
                      },
  inline27: {
                            flexDirection: 'row',
                            alignItems: 'center',
                            marginBottom: 12,
                          },
  inline28: { marginRight: 12 },
  inline29: {
                              color: '#DDD',
                              flex: 1,
                              fontSize: 16,
                            },
  inline30: {
                              backgroundColor:
                                'rgba(0,200,83,0.1)',
                              paddingHorizontal: 10,
                              paddingVertical: 4,
                              borderRadius: 8,
                            },
  inline31: {
                                color: '#00C853',
                                fontWeight: '900',
                              },
  inline32: {
                      alignItems: 'center',
                      marginTop: 12,
                      borderTopWidth: 1,
                      borderTopColor: '#222',
                      paddingTop: 20,
                    },
  inline33: {
                        color: '#555',
                        fontSize: 12,
                        fontWeight: 'bold',
                      },
  inline34: { gap: 20 },
  inline35: {
                      flexDirection: 'row',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      borderBottomWidth: 3,
                      borderBottomColor: '#000',
                      paddingBottom: 20,
                    },
  inline36: {
                          width: 140,
                          height: 45,
                          resizeMode: 'contain',
                          tintColor: '#000000',
                        },
  inline37: {
                          color: '#555',
                          fontSize: 14,
                          fontWeight: 'bold',
                          textTransform: 'uppercase',
                        },
  inline38: { alignItems: 'flex-end' },
  inline39: {
                          color: '#000',
                          fontWeight: '900',
                          fontSize: 18,
                        },
  inline40: {
                          color: '#555',
                          fontSize: 12,
                          marginTop: 4,
                        },
  inline41: {
                      backgroundColor: '#F5F5F5',
                      padding: 16,
                      borderRadius: 12,
                      borderWidth: 1,
                      borderColor: '#EEE',
                    },
  inline42: {
                        color: '#000',
                        fontWeight: '900',
                        fontSize: 16,
                        marginBottom: 4,
                      },
  inline43: {
                        color: '#333',
                        fontSize: 14,
                      },
  inline44: { fontWeight: 'bold' },
  inline45: { marginTop: 8 },
  inline46: {
                        flexDirection: 'row',
                        backgroundColor: '#000',
                        padding: 12,
                        borderRadius: 8,
                        marginBottom: 8,
                      },
  inline47: {
                          flex: 2,
                          fontWeight: 'bold',
                          color: '#FFF',
                          fontSize: 14,
                        },
  inline48: {
                          flex: 1.5,
                          fontWeight: 'bold',
                          color: '#FFF',
                          textAlign: 'center',
                          fontSize: 14,
                        },
  inline49: {
                          flex: 1,
                          fontWeight: 'bold',
                          color: '#FFF',
                          textAlign: 'center',
                          fontSize: 14,
                        },
  inline50: {
                            flex: 2,
                            color: '#000',
                            fontSize: 14,
                            fontWeight: '500',
                          },
  inline51: {
                            flex: 1.5,
                            color: '#555',
                            textAlign: 'center',
                            fontSize: 12,
                          },
  inline52: {
                            flex: 1,
                            color: '#000',
                            textAlign: 'center',
                            fontWeight: '900',
                            fontSize: 14,
                          },
  inline53: {
                      marginTop: 40,
                      borderTopWidth: 1,
                      borderTopColor: '#CCC',
                      paddingTop: 20,
                      alignItems: 'center',
                    },
  inline54: {
                        color: '#888',
                        fontSize: 10,
                        fontWeight: 'bold',
                      },
});
